---
- name: Subscribe the host
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    autosubscribe: true
  tags:
  - jboss_eap
  when: ansible_distribution == 'RedHat'

- name: Install Java
  action: "{{ ansible_pkg_mgr }} name={{ jboss_java_pkg_name }} state=latest"
  tags:
  - common

- name: Install Unzip
  action: "{{ ansible_pkg_mgr }} name=unzip state=latest"
  tags:
  - common

- name: Install initscripts
  action: "{{ ansible_pkg_mgr }} name=initscripts state=latest"
  tags:
  - common

- name: Install EPEL for CentOS
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"
  tags:
  - common
  when: transfer_method == 'csp-to-host' and ansible_distribution == 'CentOS'

